### ISSUE TITLE
Offline mode

### ISSUE THREAD

**Issue by kcmerrill** [kcmerrill/alfred#3]
Currently, every request for custom modules etc are sent to the web. 

We should download the contents each time, and if unable to find we should take a look in ~/.alfred/offline/modulename/alfred.yml

**Comment by bantl23** [comment]
I'll take a crack at this. Every time a file is pulled from the web it will be saved off into `~/.alfred/offline/<remote>/<module>/alfred.yml`. If the web is unavailable it check that location. If the file exists it uses that, otherwise it will report the original error.
