### ISSUE TITLE
Do Away With  HardCoded https://raw.githubusercontent.com/ Entries

### ISSUE THREAD

**Issue by bobhenkel** [kcmerrill/alfred#35]
Make it so that you can pass in a git location. Right now alferd only understands github. It would be nice to put modules in GitLab, Bitbucket, and xyz.

**Comment by kcmerrill** [comment]
^^^ fair point and a good feature request!

**Comment by kcmerrill** [comment]
I think this should help ... You'll just need to configure remote repositories if you want to use something other than github.

https://github.com/kcmerrill/alfred/blob/master/TFM.md#modules

**Comment by kcmerrill** [comment]
The latest version of alfred now supports remote tasks as first class ...

So you can now do something like this:
alfred http://somewhere.com:mytask arg1 arg2
