### ISSUE TITLE
Input prompt

### ISSUE THREAD

**Issue by iilyak** [kcmerrill/alfred#49]
I was looking for a way to enter strings interactively and pass the entered value to another task. Unfortunately I couldn't find a cross platform (linux/mac/win32) cli tool which would read something from keyboard (password) and echo it to stdout so I can register it in a variable. The closest thing I found is https://github.com/quininer/ttyaskpass. However sometimes the input is not the pass so it wouldn't really work. What would be your suggestion?

**Comment by kcmerrill** [comment]
hmmm, to be honest, I don't think alfred is crossplatform(I haven't tested so I don't know to be honest).  I say that 

This is a feature I am planning on adding to v0.1, but for the meantime in light of the fact I don't think alfred runs on windows(try it out! if it does let me know I'm curious) I'd recommend this for your `command` `(readline 2> /dev/null) || read`

**Comment by kcmerrill** [comment]
Leaving this open and will close when the feature is released.

**Comment by iilyak** [comment]
thank you for implementing the first version of `prompt`
