### ISSUE TITLE
Q: Allow interactive tasks

### ISSUE THREAD

**Issue by iilyak** [kcmerrill/alfred#82]
I use `alfred` to run docker images. Here is the example of alfred file https://github.com/iilyak/ddoc/blob/master/alfred.yml

It is at least 2 steps process:
- run container using alfred
- attach to running container using docker

I am looking for a solution to make this work using single command.

`docker run -it` does not work currently because `alfred` don't know how to deal with pseudo tty allocated by docker.

Most likely this is out of scope for `alfred`. However there might be some bash workarounds to make it work. Which you might know about. Any help appreciated.

**Comment by kcmerrill** [comment]
Use interactive: true

I'll get you an example and/or update the docs if need be.

**Comment by kcmerrill** [comment]
Alright, I updated the docs. I don't think you'll need to update alfred(as it's been in there for a while now) just hasn't been documented(sorry!). 

https://github.com/kcmerrill/alfred/blob/master/TFM.md#interactive--bool
