### ISSUE TITLE
Add ability to control name of config file via environment variable 

### ISSUE THREAD

**Issue by iilyak** [kcmerrill/alfred#88]
# Use case

For development in docker there might be a need to have different set of tasks. One set of tasks to run on a host system and another one inside docker container. 

# Proposal

Implement support for `ALFRED_FILE_NAME` variable to override hardcoded `alfred.yml`.
In this case the one would be able to define Docker environment variable `ENV ALFRED_FILE_NAME alfred.docker.yml`.

**Comment by kcmerrill** [comment]
This is an interesting feature. Not sure when I can get to it. 

Having said that, I use arguments in combination with `ok`, `fail` and golang templating to solve all the issues and none of mine have been too hairy.

**Comment by kcmerrill** [comment]
This ended up being trivial. You can use the `-f` flag(I documented it in the readme). By default, I'm looking for alfred/alfred.yml or some variation of alfred. 

You can use the `-f` flag now. So if you did `alfred -f bleh task.to.run` we'd look for `bleh.yml` or `bleh/*.bleh.yml`

**Comment by iilyak** [comment]
Thank you.
